export { default as Hero } from './hero'
export { default as About } from './about'
export { default as InfoSection } from './info'
export { default as ScrollerSection } from './scroller'
export { default as SmallInfoSection } from './small-info'
